import { StyleSheet } from "react-native";
import {
  heightPercentageToDP as h2dp,
  widthPercentageToDP as w2dp,
} from "react-native-responsive-screen";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    // alignItems: "center",
    marginHorizontal: w2dp(4),
    marginTop: h2dp(2),
  },
  subcontainer: {
    flex: 1,
    // alignItems: "center",
    marginHorizontal: w2dp(4),
    zIndex: 0,
  },
  containerVolunteer: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: w2dp(4),
    marginTop: h2dp(2),
  },
  root: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    zIndex: 1,
    marginBottom:h2dp(1),
  },
  leftalign: {
    textAlign: "left",
  },
  rootVolunteerHome: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: w2dp(85),
    zIndex: 1,
    marginBottom:h2dp(1),
  },
  centeredView: {
    flex: 1,
    alignItems: "center",
  },
  scrollview: {
    height: h2dp(80),
  },
  cardContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: h2dp(1),
    backgroundColor: "white",
    marginHorizontal: w2dp(1),
    // height: h2dp(13),
    borderRadius: 5,
  },
  itemFilterText: {
    fontSize: 16,
    color: "white",
    marginTop: h2dp(1),
    // justifyContent: "center",
    // textAlign: "center",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  background: {
    flex: 1,
    resizeMode: "cover",
  },
  buttonStyles: {
    backgroundColor: "#FC5A56",
    color: "black",
    borderRadius: 5,
    alignSelf: "center",
    width: w2dp(70),
    marginTop: h2dp(5),
  },
  titleStyle: {
    color: "white",
    fontSize: 26,
    fontWeight: "400",
    lineHeight: 35,
    fontFamily: "OpenSans-Regular",
  },
  dropdownContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderColor: "red",
  },
  inputError: {
    color: "red",
    marginBottom: 5,
  },
  textInput: {
    height: 50,
    borderRadius: 3,
    backgroundColor: "#FFFFFF",
  },
  textArea: {
    height: 65,
    borderRadius: 3,
    backgroundColor: "#FFFFFF",
  },
  itemFilter: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: h2dp(1),
    marginHorizontal: w2dp(1),
  },
  DateStyle: {
    height: 45,
    backgroundColor: "#FFFFFF",
  },
  callingCode: {
    fontWeight: "400",
  },
  item: {
    height: h2dp(10),
    justifyContent: "center",
    // width: w2dp(30),
    // paddingHorizontal: w2dp(20),
  },
  itemText: {
    fontSize: 25,
    color: "white",
  },
  datePickerStyle: {
    width: 345,
    height: 45,
    marginBottom: 20,
    borderColor: "white",
    backgroundColor: "#FFFFFF",
  },
  input: {
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 4,
    marginBottom: 12,
    padding: 8,
  },
  inputView: {
    justifyContent: "flex-start",
    borderColor: "#000000",
    borderWidth: 1,
    width: "100%",
    height: 50,
    marginTop: 12,
    borderRadius: 6,
    backgroundColor: "white",
  },
  dateTimePickerContainer: {
    backgroundColor: "white",
    borderRadius: 3,
    paddingVertical: 5,
    marginBottom: 25,
    height: 50,
    width: w2dp(45),
  },
  burgerText: {
    padding: 10,
    fontSize: 20,
    fontWeight: "400",
    lineHeight: 27.24,
  },
  foodhearlerText: {
    fontSize: 24,
    fontWeight: "400",
    alignSelf: "center",
    lineHeight: 35,
  },
  foodhealersHeader: {
    // backgroundColor: "white",
    borderRadius: 10,
    // height: h2dp(2),
    width: "100%",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
    zIndex: 9999,
  },
  subHeading: {
    // marginLeft: w2dp(7),
    marginBottom: h2dp(1.3),
    fontSize: h2dp(2),
    color: "white",
  },
  mapContent: {
    color: "white",
    fontSize: h2dp(2.5),
    alignSelf: "center",
  },
  imageStyle: {
    borderRadius: 10,
    width: w2dp(85),
    height: h2dp(15),
  },
  mapImage: {
    borderRadius: 10,
    marginTop: h2dp(1),
    width: w2dp(85),
    // height: h2dp(15),
    alignSelf: "center",
  },
  title: {
    backgroundColor: "white",
    opacity: 0.9,
    width: w2dp(85),
    // height: "20%",
    position: "absolute",
    bottom: 0,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
  },
  textStyle: {
    textAlign: "center",
    fontSize: 26,
    lineHeight: 35,
    fontWeight: "normal",
    fontStyle: "normal",
    marginTop: 13,
  },
  horizonatalView: {
    display: "flex",
    flexDirection: "row",
    // justifyContent: "space-between",
    // alignItems: "flex-end",
    // marginTop: h2dp(2),
  },
  headerContainer: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    width: "100%",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginTop: h2dp(-50),
    position: "absolute",
    bottom: 0,
    height: h2dp(10),
  },
  card: {
    backgroundColor: "white",
    width: w2dp(85),
    marginBottom: h2dp(1),
    alignSelf: "center",
  },
  cardText: {
    backgroundColor: "transparent",
    width: w2dp(85),
    borderRadius: h2dp(3),
    marginBottom: 10,
    height: h2dp(45),
    alignSelf: "center",
  },
  description: {
    marginTop: h2dp(2),
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  buttonHistoryStyles: {
    backgroundColor: "#FFFFFF",
    color: "black",
    borderRadius: 5,
    width: w2dp(70),
    marginTop: h2dp(3),
    alignSelf: "center",
  },
  buttonMainStyles: {
    backgroundColor: "#FC5A56",
    color: "black",
    borderRadius: 5,
    width: w2dp(70),
    marginTop: h2dp(5),
    alignSelf: "center",
  },
  titleMainStyle: {
    color: "black",
    fontSize: 26,
    lineHeight: 35,
    fontFamily: "OpenSans-Regular",
  },
  toggle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: h2dp(1),
    marginLeft: w2dp(1),
  },
  tabStyle: {
    borderColor: "#EDC258",
  },
  boldText: {
    fontWeight: "300",
    fontSize: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    paddingHorizontal: w2dp(2),
  },
  modalContent: {
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 20,
    marginHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 8,
  },
  HeaderText: {
    fontSize: 20,
    textAlign: "left",
    color: "white",
    fontWeight: "bold",
  },
  modalText: {
    fontSize: 16,
    textAlign: "left",
    color: "white",
    marginTop: 15,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 30,
  },
  markerIcon: {
    width: 40,
    height: 40,
  },
  mapContainer: {
    height: h2dp(65),
    marginTop: h2dp(3),
    borderRadius: 10,
  },
  dropdown1BtnStyle: {
    marginTop: 15,
    // marginLeft: 45,
    width: "70%",
    height: 50,
    backgroundColor: "#FFF",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#D1D1D6",
  },
  dropdown1BtnTxtStyle: { color: "#B50000", textAlign: "left", fontSize: 14 },
  dropdown1DropdownStyle: {
    backgroundColor: "#EFEFEF",
    color: "black",
    borderRadius: 4,
    height: 180,
    fontSize: 14,
    borderColor: "blue",
  },
  dropdown1RowStyle: {
    backgroundColor: "#EFEFEF",
    color: "#B50000",
    borderBottomColor: "#D1D1D6",
    borderRadius: 5,
  },
  dropdown1RowTxtStyle: { color: "black", textAlign: "center", fontSize: 10 },
  calendarView: {
    width: w2dp(85),
    alignSelf: "center",
    marginTop: h2dp(1),
    // borderWidth:13,
    borderRadius: 10,
  },
  tabLabel: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  tabIndicator: {
    backgroundColor: "white",
    height: 2,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    width: w2dp(86),
    height: h2dp(6),
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#f5f5f5",
  },
  icon: {
    paddingHorizontal: 10,
  },
  touchableView: {
    borderRadius: 15,
    marginTop: h2dp(4),
    width: "85%",
    backgroundColor: "white",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  timerIcon: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: h2dp(2),
  },
  heading: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    marginLeft: w2dp(4),
  },
});
