import { StyleSheet } from "react-native";
import {
  heightPercentageToDP as h2dp,
  widthPercentageToDP as w2dp,
} from "react-native-responsive-screen";
import { Platform } from "react-native";

export const styles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: w2dp(4),
  },
  container: {
    flex: 1,
    marginHorizontal: w2dp(4),
  },
  subcontainer: {
    flex: 1,
    marginHorizontal: w2dp(4),
    zIndex: 0,
  },
  header: {
    position: "absolute",
    top: 0,
    left: h2dp(-2.6),
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: w2dp(4.5),
    paddingTop: h2dp(3),
    paddingBottom: h2dp(2),
  },
  headerTitle: {
    fontSize: w2dp(5),
    color: "white",
    fontWeight: "bold",
  },
  containerVolunteer: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: w2dp(4),
  },
  root: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    zIndex: 1,
    marginBottom: h2dp(1),
  },
  burgerIconContainer: {
    position: "absolute",
    right: 0,
    zIndex: 10,
  },
  leftalign: {
    textAlign: "left",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
    zIndex: 9999,
  },
  horizonatalView: {
    flexDirection: "row",
  },
  profileDetailsText2: {
    paddingLeft: w2dp(1.2),
    marginTop: h2dp(-0.2),
    fontSize: h2dp(2),
    color: "white",
  },
  itemFilterText: {
    fontSize: h2dp(1.6),
    color: "white",
    marginTop: h2dp(1),
  },
  filterNameText: {
    fontSize: h2dp(1.6),
    color: "white",
    marginTop: h2dp(1),
    fontWeight: "bold",
  },
  titleStyle: {
    color: "white",
    fontSize: h2dp(2.2),
  },
  HeaderText: {
    fontSize: h2dp(2),
    textAlign: "left",
    color: "white",
    fontWeight: "bold",
  },
  modalText: {
    fontSize: h2dp(1.8),
    textAlign: "left",
    color: "white",
    marginTop: h2dp(2),
  },
  textStyle: {
    textAlign: "center",
    fontSize: h2dp(2),
    lineHeight: Platform.OS === "ios" ? h2dp(3) : h2dp(3.5),
    fontWeight: "normal",
  },
  boldText: {
    fontWeight: "300",
    fontSize: h2dp(2),
  },
  subHeading: {
    marginBottom: h2dp(1.3),
    fontSize: h2dp(2),
    color: "white",
  },
  mapContent: {
    color: "white",
    fontSize: h2dp(2.5),
    alignSelf: "center",
  },
  menuContainer: {
    position: "absolute",
    right: w2dp("5%"),
    top: Platform.OS === "ios" ? h2dp("6%") : h2dp("5%"),
    backgroundColor: "white",
    borderColor: "black",
    borderWidth: 0.5,
    borderRadius: 5,
    zIndex: 9999,
    elevation: 5,
    minWidth: w2dp("30%"),
  },
  burgerText: {
    padding: h2dp(1),
    fontWeight: "400",
    lineHeight: h2dp(2.7),
  },
  foodhearlerText: {
    fontSize: h2dp(2.4),
    fontWeight: "400",
    alignSelf: "center",
    lineHeight: h2dp(3.5),
  },
  itemText: {
    fontSize: h2dp(2.5),
    color: "white",
    fontWeight: "bold",
  },
  itemTextDriver: {
    fontSize: h2dp(2.5),
    color: "black",
  },
  titleMainStyle: {
    color: "white",
    fontSize: h2dp(2.6),
    lineHeight: h2dp(3.5),
    fontFamily: "OpenSans-Regular",
  },
  ingredient: {
    marginBottom: h2dp(0.5),
    color: "white",
    fontSize: h2dp(2),
  },
  underlineTextStyle: {
    textDecorationLine: "underline",
  },
  eventTitle: {
    marginTop: h2dp(1.5),
    fontSize: h2dp(2),
    marginLeft: w2dp(2),
  },
  centeredView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  centeredalignView: {
    flex: 1,
    alignItems: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    paddingHorizontal: w2dp(4),
  },
  modalView: {
    margin: w2dp(5),
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderRadius: w2dp(5),
    padding: w2dp(8),
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalContent: {
    paddingHorizontal: w2dp(5),
    marginHorizontal: w2dp(5),
    paddingVertical: h2dp(2),
    borderRadius: w2dp(2),
    backgroundColor: "white",
    padding: h2dp(3),
  },
  headerContainer: {
    flexDirection: "column",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    width: "100%",
    borderTopLeftRadius: w2dp(2.5),
    borderTopRightRadius: w2dp(2.5),
    marginTop: h2dp(-5),
    position: "absolute",
    bottom: 0,
    height: h2dp(10),
  },
  subHeader: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginLeft: w2dp(1),
  },
  heading: {
    flexDirection: "column",
    justifyContent: "flex-start",
    marginLeft: w2dp(4),
  },
  dateContainer: {
    marginTop: h2dp(4),
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginLeft: w2dp(8),
  },

  // Scroll and list styles
  scrollview: {
    height: h2dp(75),
  },
  eventsContainer: {
    flexDirection: "row",
    marginBottom: h2dp(2),
  },
  eventName: {
    justifyContent: "flex-start",
    width: w2dp(80),
  },
  cardContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: h2dp(2),
    backgroundColor: "white",
    marginHorizontal: w2dp(1),
    borderRadius: w2dp(1),
  },
  itemFilter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: h2dp(1),
    marginHorizontal: w2dp(1),
  },
  item: {
    minHeight: h2dp(10),
    justifyContent: "center",
  },
  card: {
    marginTop: h2dp(5),
    backgroundColor: "white",
    width: w2dp(85),
    marginBottom: h2dp(1),
    alignSelf: "center",
    borderRadius: w2dp(2),
  },
  cardText: {
    backgroundColor: "transparent",
    width: w2dp(85),
    borderRadius: h2dp(3),
    marginBottom: h2dp(1),
    height: h2dp(45),
    alignSelf: "center",
  },
  foodhealersHeader: {
    borderRadius: w2dp(2.5),
    width: "100%",
  },
  bottomButtonContainer: {
    // justifyContent: "center",
    bottom: 20,
  },
  textInput: {
    height: h2dp(6),
    marginBottom: h2dp(1),
    backgroundColor: "white",
    borderRadius: w2dp(1),
    paddingHorizontal: w2dp(3),
  },
  textArea: {
    height: h2dp(8),
    borderRadius: w2dp(0.75),
    backgroundColor: "#FFFFFF",
  },
  DateStyle: {
    height: h2dp(5.5),
    backgroundColor: "#FFFFFF",
    borderRadius: w2dp(1),
  },
  input: {
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: w2dp(1),
    marginBottom: h2dp(1.5),
    padding: w2dp(2),
  },
  inputView: {
    justifyContent: "flex-start",
    borderColor: "#000000",
    borderWidth: 1,
    width: "100%",
    height: h2dp(6),
    marginTop: h2dp(1.5),
    borderRadius: w2dp(1.5),
    backgroundColor: "white",
    paddingHorizontal: w2dp(3),
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: w2dp(2),
    width: w2dp(86),
    height: h2dp(6),
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#f5f5f5",
  },
  icon: {
    paddingHorizontal: w2dp(3),
  },
  inputError: {
    color: "#ff6e75",
    marginBottom: h2dp(0.5),
    fontSize: h2dp(1.5),
  },
  datePickerStyle: {
    width: w2dp(85),
    height: h2dp(6),
    marginBottom: h2dp(2.5),
    borderColor: "white",
    backgroundColor: "#FFFFFF",
    borderRadius: w2dp(1),
  },
  dateTimePickerContainer: {
    backgroundColor: "white",
    borderRadius: w2dp(0.75),
    paddingVertical: h2dp(0.5),
    marginBottom: h2dp(3),
    height: h2dp(6),
    width: w2dp(45),
  },
  calendarView: {
    width: w2dp(85),
    alignSelf: "center",
    marginTop: h2dp(1),
    borderRadius: w2dp(2.5),
  },
  dropdownContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "red",
  },
  dropdown1BtnStyle: {
    marginTop: h2dp(1.5),
    width: "70%",
    height: h2dp(6),
    backgroundColor: "#FFF",
    borderRadius: w2dp(1.25),
    borderWidth: 1,
    borderColor: "#D1D1D6",
  },
  dropdown1BtnTxtStyle: {
    color: "#B50000",
    textAlign: "left",
    fontSize: h2dp(1.8),
  },
  dropdown1DropdownStyle: {
    backgroundColor: "#EFEFEF",
    color: "black",
    borderRadius: w2dp(1),
    height: h2dp(22),
    fontSize: h2dp(1.8),
    borderColor: "blue",
  },
  dropdown1RowStyle: {
    backgroundColor: "#EFEFEF",
    color: "#B50000",
    borderBottomColor: "#D1D1D6",
    borderRadius: w2dp(1.25),
    height: h2dp(5),
  },
  dropdown1RowTxtStyle: {
    color: "black",
    textAlign: "center",
    fontSize: h2dp(1.8),
  },
  callingCode: {
    fontWeight: "400",
    fontSize: h2dp(1.8),
  },
  buttonStyles: {
    backgroundColor: "#FC5A56",
    borderRadius: w2dp(2),
    marginTop: h2dp(3),
    marginHorizontal: h2dp(2),
    height: h2dp(6),
    justifyContent: "center",
  },
  nextButtonStyles: {
    backgroundColor: "#FC5A56",
    color: "black",
    borderRadius: w2dp(1.25),
    alignSelf: "center",
    width: w2dp(50),
    marginTop: h2dp(5),
    height: h2dp(6),
    justifyContent: "center",
  },
  buttonHistoryStyles: {
    backgroundColor: "gray",
    color: "black",
    borderRadius: w2dp(2),
    width: w2dp(90),
    marginTop: h2dp(3),
    alignSelf: "center",
    height: h2dp(6),
    justifyContent: "center",
  },
  buttonMainStyles: {
    backgroundColor: "#FC5A56",
    color: "black",
    borderRadius: w2dp(2),
    width: w2dp(90),
    marginTop: h2dp(5),
    alignSelf: "center",
    height: h2dp(6),
    justifyContent: "center",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: h2dp(3),
  },

  // Image styles
  background: {
    flex: 1,
    resizeMode: "cover",
  },
  imageStyle: {
    borderRadius: w2dp(2.5),
    width: w2dp(85),
    height: h2dp(15),
  },
  mapImage: {
    borderRadius: w2dp(2.5),
    marginTop: h2dp(1),
    width: w2dp(85),
    alignSelf: "center",
  },
  markerIcon: {
    width: w2dp(10),
    height: w2dp(10),
  },
  title: {
    backgroundColor: "white",
    opacity: 0.9,
    width: w2dp(85),
    position: "absolute",
    bottom: 0,
    borderBottomRightRadius: w2dp(2.5),
    borderBottomLeftRadius: w2dp(2.5),
    padding: w2dp(2),
  },

  mapContainer: {
    height: h2dp(65),
    marginTop: h2dp(3),
    borderRadius: w2dp(2.5),
  },
  fixedButtonContainer: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    zIndex: 10,
  },
  toggle: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginLeft: w2dp(1),
  },
  tabStyle: {
    borderColor: "#EDC258",
  },
  tabLabel: {
    color: "white",
    fontSize: h2dp(1.8),
    fontWeight: "bold",
  },
  tabIndicator: {
    backgroundColor: "white",
    height: h2dp(0.3),
  },

  // Touchable and event styles
  touchableView: {
    borderRadius: w2dp(4),
    marginTop: h2dp(4),
    width: "85%",
    backgroundColor: "white",
    flexDirection: "row",
    justifyContent: "flex-start",
    padding: w2dp(3),
  },
  timerIcon: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: h2dp(2),
  },
  eventCon: {
    backgroundColor: "white",
    height: h2dp(5),
    width: w2dp(60),
    marginTop: h2dp(2),
    marginLeft: w2dp(5),
    borderRadius: w2dp(1.25),
    justifyContent: "center",
  },
  date: {
    color: "white",
    height: h2dp(7),
    marginLeft: w2dp(5),
    borderRadius: w2dp(1.25),
  },
  description: {
    marginTop: h2dp(2),
    flexDirection: "column",
    justifyContent: "center",
  },
  vehicledetailsCard: {
    width: w2dp(90),
    backgroundColor: "white",
    padding: h2dp(2),
    margin: h2dp(2),
    borderRadius: h2dp(1),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    marginHorizontal: "auto",
  },
});
